---
title: The Butler
baseline: Your blogging assistant
description: A ready to use static blog, powered by Cecil.
baseurl: "/"
canonicalurl: true
keywords:
- Cecil
- Static Site Generator
- SSG
author: Kai Gr√∂teke
date:
  format: j F Y
  timezone: Europe/Paris
theme:
- hyde
- netlify
- netlify-cms
hyde:
  sidebar:
    sticky: true
  theme: cecil
  reverse: false